FROM node:24-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

COPY package*.json .

RUN pnpm install

# In dev, we mount the source code
COPY . .

EXPOSE 3000

# Run in dev mode for hot-reloading
CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]
