x-s3-data: &s3-defaults
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "REPLACETHISWITHSOMETHINGSECURE"
  MINIO_ENDPOINT: "http://minio:9000"
  S3_BUCKET_NAME: "phantasia"
  S3_DOMAIN: "i.uwu.local"

x-postgres-data: &postgres-defaults
  POSTGRES_HOST: "db"
  POSTGRES_USER: "phantasiauser"
  POSTGRES_PASSWORD: "REPLACETHISWITHSOMETHINGSECURE"
  POSTGRES_DB: "phantasia"

x-grafana-data: &grafana-defaults
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "thisisreallysecurepasswordno"

services:
  phantasia-frontend:
    # image:
    build: 
      context: frontend
      dockerfile: ./Dockerfile
    container_name: phantasia-frontend
    restart: unless-stopped
    depends_on:
      - phantasia-api
    
  phantasia-api:
    # image:
    build:
      context: api
      dockerfile: ./Dockerfile
    container_name: phantasia-api
    restart: unless-stopped
    depends_on:
      - db
      - minio
    environment:
      <<: 
        - *s3-defaults
        - *postgres-defaults

  db:
    image: postgres:16-alpine
    container_name: phantasia-db
    restart: always
    environment:
      <<:
        - *postgres-defaults
    volumes:
      - db:/var/lib/postgresql/data

  phantasia-nginx:
    image: nginx:1.29.0-alpine
    container_name: phantasia-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certificates:/etc/nginx/ssl/
    depends_on:
      - phantasia-frontend
      - phantasia-api
      - minio
  minio:
    image: minio/minio
    container_name: phantasia-minio
    volumes:
      - minio_data:/data
    environment:
      <<:
        - *s3-defaults
    command: server /data

  loki:
    image: grafana/loki
    container_name: phantasia-loki
    restart: always
    ports:
      - 3100:3100
    volumes:
      - ./statistics/loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki

  prometheus:
    image: prom/prometheus
    container_name: phantasia-prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
  
  grafana:
    image: grafana/grafana:12.4.0
    container_name: phantasia-grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      <<:
        - *grafana-defaults
    volumes:
      - ./statistics/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./statistics/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - loki

volumes:
  db:
  minio_data:
  loki_data:
  prometheus_data:

