class UserPermissions:
    USER_ALL = "USER_ALL"
    
    USER_UPLOAD = "USER_UPLOAD"
    DELETE_OTHER_UPLOADS = "DELETE_OTHER_UPLOADS"

    MODIFY_OTHER_USERS = "MODIFY_OTHER_USERS"
    
    SUPERUSER = "SUPERUSER"

    BAN_USERS = "BAN_USERS"
    
    INVITE_CREATE = "INVITE_CREATE"
    INVITE_DELETE = "INVITE_DELETE"