class UserPermissions:
    USER_ALL = "USER_ALL"
    USER_UPLOAD = "USER_UPLOAD"
    BAN_USERS = "BAN_USERS"
    MODIFY_OTHER_USERS = "MODIFY_OTHER_USERS"
    SUPERUSER = "SUPERUSER"

    INVITE_CREATE = "INVITE_CREATE"
    INVITE_DELETE = "INVITE_DELETE"
    INVITE_MANAGE = "INVITE_MANAGE"