map $host $base_domain {
    ~^(?:.+\.)?([^.]+\.(?:co\.uk|org\.uk|gov\.uk))$ $1;
    ~^(?:.+\.)?([^.]+\.[^.]+)$ $1;
}

# Default gateway (HTTP)
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    return 444;
}

# Redirect all HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name uwu.local uwu.so www.uwu.so staging.uwu.so api.uwu.local api.uwu.so api.staging.uwu.so i.uwu.local i.uwu.so i.staging.uwu.so;

    return 301 https://$host$request_uri;
}

# Frontend HTTPS
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name uwu.local uwu.so www.uwu.so staging.uwu.so;

    ssl_certificate     /etc/nginx/ssl/uwu.local.pem;
    ssl_certificate_key /etc/nginx/ssl/uwu.local-key.pem;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Base-Host $base_domain;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://phantasia-frontend:3000/;
    }
}

# API HTTPS
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name api.uwu.local api.uwu.so api.staging.uwu.so;

    ssl_certificate     /etc/nginx/ssl/uwu.local.pem;
    ssl_certificate_key /etc/nginx/ssl/uwu.local-key.pem;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Base-Host $base_domain;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://phantasia-api:4444/;
    }
}

# MinIO HTTPS
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name i.uwu.local i.uwu.so i.staging.uwu.so;

    ssl_certificate     /etc/nginx/ssl/uwu.local.pem;
    ssl_certificate_key /etc/nginx/ssl/uwu.local-key.pem;

    location / {
        rewrite ^/(.*)$ /phantasia/$1 break;

        proxy_pass http://minio:9000;

        proxy_set_header Host $host;
        proxy_set_header X-Base-Host $base_domain;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        limit_except GET HEAD {
            deny all;
        }
    }
}
