map $host $base_domain {
    ~^(?:.+\.)?([^.]+\.(?:co\.uk|org\.uk|gov\.uk))$ $1;
    ~^(?:.+\.)?([^.]+\.[^.]+)$ $1;
}


# Default gateway
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    return 444;
}

# Frontend
server {
    listen 80;
    listen [::]:80;

    server_name uwu.local uwu.so www.uwu.so staging.uwu.so;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Base-Host $base_domain;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://phantasia-frontend:3000/;
    }
}

# API
server {
    listen 80;
    listen [::]:80;

    server_name api.uwu.local api.uwu.so api.staging.uwu.so;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Base-Host $base_domain;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://phantasia-api:4444/;
    }
}

# MinIO
server {
    listen 80;
    listen [::]:80;
    server_name i.uwu.local i.uwu.so i.staging.uwu.so;

    location / {
        rewrite ^/(.*)$ /phantasia/$1 break;

        proxy_pass http://minio:9000;
        
        proxy_set_header Host $host;
        proxy_set_header X-Base-Host $base_domain;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        limit_except GET HEAD {
            deny all;
        }
    }
}